### ISSUE TITLE
enhancement issue

### ISSUE THREAD

**Issue by swiftfile** [scramble-robot/JuniorRobotTeam2022#1]
関数実行するたびにeanbleを見に行かなくなったので、見通しがよくなった気がします！
コメントも揃っててみやすいです！

最近こういう小さいところにしか口出せてなくてあれなのですが、単位がある定数は単位もコメントに含めると嬉しい気がします。
`通信速度(bps)` が良さそうです。
https://github.com/scramble-robot/JuniorRobotTeam2022/blob/258f0f2a968864c52187f2357f83fafe81a9993a/JuniorRoboSample_main/JuniorRoboSample_main.ino#L28

---
1_Yについてですが、左右スティックの命名が1,2なんですよね... もし配列とかで数字を扱ってないならL(eft)_Y,R(ight)_Yのほうが良いかと思うのですが、どうでしょう...？
https://github.com/scramble-robot/JuniorRobotTeam2022/blob/258f0f2a968864c52187f2357f83fafe81a9993a/JuniorRoboSample_main/JuniorRoboSample_main.ino#L239

**Comment by vista238** [comment]
> 単位がある定数は単位もコメントに含める

通信速度の単位をコメントに追記しました
https://github.com/scramble-robot/JuniorRobotTeam2022/commit/e667284ff2548c4d81289de211b1e1c1e8b6a803

> 左右スティックの命名

コメントを1,2から左,右に修正しました
https://github.com/scramble-robot/JuniorRobotTeam2022/commit/dd9986424210dc414c11b9e5585754865315de20
